- name: install influx db
  become: yes
  apt:
    name: influxdb
    update_cache: yes
    state: present

- name: install additional package
  become: yes
  apt:
    name: influxdb-client
    update_cache: yes
    state: present

- name: make sure influxdb running
  become: yes
  service:
    name: influxdb
    state: started

- name: package telegraf
  become: yes
  get_url:
    url: https://dl.influxdata.com/telegraf/releases/telegraf_1.17.0-1_amd64.deb
    dest: /opt/telegraf_1.17.0-1_amd64.deb
  tags:
    - telegraf

- name: install telegraf package
  become: yes
  apt:
    deb: /opt/telegraf_1.17.0-1_amd64.deb
  tags:
    - telegraf

- name: config telegraf
  become: yes
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart telegraf
  tags:
    - telegraf

# - name: setup reverse proxy for influxdb
#   become: yes
#   template:
#     src: grafana.conf.j2
#     dest: /etc/nginx/sites-available/grafana.conf
#   notify:
#     - restart nginx
#   tags:
#     - setup_reverse_proxy
