---
  - name: create grafana working directory
    become: yes
    file:
      path: /opt/docker/grafana
      state: directory
      owner: 472
      group: 472
      mode: u+rwx,g+rx,o+rwx

  - name: create container
    become: yes
    docker_container:
      name: grafana-server
      image: "grafana/grafana"
      volumes:
        - /opt/docker/grafana:/var/lib/grafana
      published_ports:
        - "{{ grafana_docker_port }}:3000"
      env:
        GF_SERVER_ROOT_URL: "http://localhost:{{ grafana_docker_port }}/grafana"
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  - name: update reverse proxy for garfana_docker
    become: yes
    template:
      src: grafana.conf.j2
      dest: /etc/nginx/sites-available/grafana.conf
    notify:
      - restart nginx
