---
- name: gather stuff
  hosts: all
  become: yes
  tasks:
    - setup:

- name: setup dns_servers + exporter
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - dns_servers

- name: fix resolv.conf
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - resolv
  tags:
    - resolv

- name: setup web_servers
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx

- name: sites-enabled
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - sites-enabled
  tags:
    - sites-enabled
    - expt

- name: setup docker
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - docker

- name: setup db_servers + exporter
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter

- name: setup app_servers (with docker)
  hosts: app_servers
  become: yes
  gather_facts: no
  roles:
    - agama_docker
  tags:
    - agama_docker

- name: install haproxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy

- name: install keepalived
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
  tags:
    - keepalived

- name: setup prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus

- name: influxdb + stuff
  hosts: influxdb
  become: yes
  roles:
    - influxdb
    - pinger
    - rsyslog
  tags:
    - inf

- name: grafana (with docker)
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana_docker
  tags:
    - grafana

- name: extra exporters
  hosts: exporters
  become: yes
  gather_facts: no
  roles:
    - node_exporter
    - nginx_exporter
  tags:
    - expt1
- name: backup
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags:
    - backup
