---
- name: gather stuff
  hosts: all
  become: yes
  tasks:
    - setup:

- name: setup dns_servers
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter

- name: setup dns_servers
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - resolv

- name: setup db_servers
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter

- name: setup web_servers
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - nginx
    - nginx_exporter

- name: setup docker + node_exporter
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - docker
    - node_exporter

- name: setup app_servers (with docker)
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - agama_docker

- name: setup prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus

- name: influxdb + stuff
  hosts: influxdb
  become: yes
  roles:
    - influxdb
    - pinger
    - rsyslog
  tags:
    inf
- name: grafana (with docker)
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana_docker
  tags:
    - grafana

- name: fix nginx sites
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - sites-enabled
  tags:
    - fix-sites

- name: install haproxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - haproxy
  tags:
    - haproxy
