- name: install nginx
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes

# - name: setup reverse nginx proxy
#   become: yes
#   template:
#     src:
#     dest:
#   notify:
#     - restart nginx

- name: install prometheus
  become: yes
  apt:
    name: prometheus
    state: present
    update_cache: yes

- name: configure prometheus
  become: yes
  template:
    src: prometheus.yaml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: adjust prometheus service
  become: yes
  template:
    src: prometheus
    dest: /etc/default/prometheus
  notify:
    - restart prometheus
