- name: restart bind_exporter
  service:
    name: bind_exporter
    state: restarted

- name: restart bind9
  service:
    name: bind9
    state: restarted
    
- name: daemon reload
  shell: systemctl daemon-reload
- name: hash
  shell: hash -r
