- name: install mysql
  become: yes
  apt:
    pkg:
      - mysql-server
      - python3-pymysql
    state: present

- name: create dedicated group
  become: yes
  group:
    name: "{{dedicated_exporter_group}}"
    state: present
    system: yes

- name: create dedicated user
  become: yes
  user:
    name: "{{dedicated_exporter_user}}"
    group: "{{dedicated_exporter_group}}"
    shell: /sbin/nologin

- name: Check that the mysql_exporter file exists
  stat:
    path: /opt/mysqld_exporter-0.12.1.linux-amd64.tar.gz
  register: stat_result

- name: download mysql_exporter
  become: yes
  get_url:
    url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: create repo for mysql_exporter
  become: yes
  file:
    path: /opt/sql_exporter
    state: directory
    mode: '0755'

- name: untar
  become: yes
  unarchive:
    src: /opt/mysqld_exporter-0.12.1.linux-amd64.tar.gz
    dest: /opt/sql_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: create sql user for exporter
  become: yes
  mysql_user:
    name: "{{mysql_exporter_user}}"
    password: "{{mysql_exporter_password}}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: '*.*:ALL'
    state: present

- name: systemd sql_exporter
  become: yes
  template:
    src: sql_exporter.service.j2
    dest: /etc/systemd/system/sql_exporter.service
  notify:
    - restart sql_exporter
    - daemon reload
    - hash

- name: start exporter
  become: yes
  service:
    name: sql_exporter
    state: started
    enabled: yes
