- name: install mysql
  become: yes
  apt:
    pkg:
      - mysql-server
      - python3-pymysql
    state: present
    update_cache: yes
- name: make sure mysql running
  become: yes
  service:
    name: mysql
    state: started
    
- name: configure mysql
  become: yes
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql
  tags:
    - update_cnf
- name: create mysql database
  become: yes
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: create mysql user
  become: yes
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"

- name: create replication user
  become: yes
  mysql_user:
    name: replication
    password: "{{ replication_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    state: present
  tags:
    - replication
