- name: No default nginx
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx

- name: configure nginx homepage for grafana
  become: yes
  template:
    src: grafana.conf.j2
    dest: /etc/nginx/sites-available/grafana.conf
  notify:
    - restart nginx
    
- name: symlink page
  become: yes
  file:
    src: /etc/nginx/sites-available/grafana.conf
    dest: /etc/nginx/sites-enabled/grafana.conf
    state: link
  notify:
    - restart nginx
