jobs:
  - name: node
    port: 9100
    targets:
      - vm01.skaldr.io
      - vm02.skaldr.io
      - vm03.skaldr.io
  - name: bind
    port: 9119
    targets:
      - vm01.skaldr.io
      - vm02.skaldr.io
      - vm03.skaldr.io
  - name: mysql
    port: 9104
    targets:
      - vm02.skaldr.io
      - vm03.skaldr.io
  - name: nginx
    port: 9113
    targets:
      - vm01.skaldr.io
      - vm02.skaldr.io
      - vm03.skaldr.io
  - name: haproxy
    port: 9101
    targets:
      - vm02.skaldr.io
      - vm03.skaldr.io
  - name: keepalived
    port: 9165
    targets:
      - vm02.skaldr.io
      - vm03.skaldr.io
