- name: install bind9
  become: yes
  apt:
    name: bind9
- name: start bind9 if not running
  become: yes
  service:
    name: bind9
    state: started

- name: config bind options
  become: yes
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
  - restart bind
  - check conf

- name: config bind local
  become: yes
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
  - restart bind
  - check conf

- name: upload bind zone
  become: yes
  template:
    src: db.skaldr.j2
    dest: /etc/bind/db.skaldr
  notify:
  - bind reload db

- name: fix resolv.conf
  become: yes
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
