- name: check conf
  become: yes
  shell: named-checkconf

- name: restart bind
  become: yes
  service:
    name: bind9
    state: restarted

- name: bind reload db
  become: yes
  shell: rndc reload
