- name: restart systemd
  become: yes
  shell: "systemctl daemon-reload"

- name: restart prometheus
  become: yes
  service:
    name: prometheus
    state: restarted

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted
