- name: install bind9
  become: yes
  apt:
    name: bind9
    state: present
    update_cache: yes

- name: start bind9 if not running
  become: yes
  service:
    name: bind9
    state: started

- name: config bind options
  become: yes
  template:
    src: templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify:
  - restart bind
  - check conf

- name: Bind zone config master
  become: yes
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify:
  - restart bind
  when: inventory_hostname in groups['dns_masters']

- name: Bind zone config slave
  become: yes
  template:
    src: named.conf.local.slave.j2
    dest: /etc/bind/named.conf.local
  notify:
  - restart bind
  when: inventory_hostname in groups['dns_slaves']

- name: upload zone
  become: yes
  template:
    src: db.skaldr.j2
    dest: /var/lib/bind/db.{{ domain }}
    backup: yes
  notify:
  - bind reload db
  when: inventory_hostname in groups['dns_masters']

- name: install dnspython
  become: yes
  apt:
    name: python3-dnspython
    update_cache: yes
    state: present

- name: update record
  become: yes
  nsupdate:
    key_name: "dns_update"
    key_secret: "{{ dns_update_secret }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_masters'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ domain }}"
    record: "hello"
    value: "192.168.1.99"
  when: inventory_hostname in groups['dns_masters'][0]
  tags:
    - add_record
# - name: fix resolv.conf
#   become: yes
#   template:
#     src: resolv.conf
#     dest: /etc/resolv.conf
#   tags:
#     - slave
